services:
  - type: web
    name: bybit-ai-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BYBIT_API_KEY
        value: "PV0ATOPILU1gAPe7JG"
      - key: BYBIT_API_SECRET
        value: "ZusEtV7pnqbHMoVB4Oej5XKd2gUHt00n7EeQ"
      - key: BYBIT_DEMO
        value: "True"
      - key: TELEGRAM_BOT_TOKEN
        value: "8363627370:AAE-1MphxrahFrRkgOSjBn_KnUYEJBL4cb0"
      - key: TELEGRAM_CHAT_ID
        value: "7840645929"
      - key: LEVERAGE
        value: "5"
      - key: TRADE_AMOUNT_USDT
        value: "100"
      - key: MAX_CONCURRENT_TRADES
        value: "10"
